@echo off
title TrueNexus Setup
cd /d "%~dp0"
echo [1/3] Installing Python dependencies...
python -m pip install -r requirements.txt
echo [2/3] Writing bundled tool paths (tools\TrueCollider + tools\TrueMkeyCollider)...
python -c "import json; from pathlib import Path; root=Path('.').resolve(); tc=root/'tools'/'TrueCollider'; mk=root/'tools'/'TrueMkeyCollider'; p=Path('presets'); p.mkdir(exist_ok=True); cfg={'truecollider_exe': str(tc/'keyhunt.exe'), 'truecollider_cuda': str(tc/'keyhunt_cuda.exe'), 'truemkey_exe': str(mk/'TrueMkeyCollider.exe'), 'workdir': str(tc), 'theme': 'Obsidian Gold', 'auto_configured': True}; (p/'user_settings.json').write_text(json.dumps(cfg, indent=2), encoding='utf-8'); print('settings ->', tc); print('keyhunt:', (tc/'keyhunt.exe').exists()); print('mkey:', (mk/'TrueMkeyCollider.exe').exists())"
echo [3/3] Ideas catalog check...
python -c "from truenexus.ideas_catalog import completeness_report; print(completeness_report())"
echo.
echo Launching TrueNexus...
start "" python -m truenexus
pause
