"""Visual themes for TrueNexus."""

from __future__ import annotations

THEMES: dict[str, dict] = {
    "Obsidian Gold": {
        "mode": "dark",
        "fg": "#0B0E14",
        "card": "#121722",
        "accent": "#D4A017",
        "accent2": "#F0C75E",
        "text": "#E8ECF1",
        "muted": "#8B93A7",
        "success": "#3DDC97",
        "danger": "#FF5C5C",
        "console_bg": "#070A10",
        "console_fg": "#C8FACC",
    },
    "Arctic Steel": {
        "mode": "light",
        "fg": "#F4F7FB",
        "card": "#FFFFFF",
        "accent": "#1F6FEB",
        "accent2": "#388BFD",
        "text": "#0D1117",
        "muted": "#57606A",
        "success": "#1A7F37",
        "danger": "#CF222E",
        "console_bg": "#0D1117",
        "console_fg": "#7EE787",
    },
    "Plasma Cyan": {
        "mode": "dark",
        "fg": "#061018",
        "card": "#0C1A24",
        "accent": "#00E5FF",
        "accent2": "#80F0FF",
        "text": "#E6F7FF",
        "muted": "#7AA0B2",
        "success": "#00FF9C",
        "danger": "#FF4D6D",
        "console_bg": "#03080C",
        "console_fg": "#7DFFB3",
    },
    "Ember Forge": {
        "mode": "dark",
        "fg": "#140A08",
        "card": "#1E100C",
        "accent": "#FF6A3D",
        "accent2": "#FFB347",
        "text": "#FFEDE6",
        "muted": "#B08978",
        "success": "#9BE564",
        "danger": "#FF3B3B",
        "console_bg": "#0A0504",
        "console_fg": "#FFD6A5",
    },
    "Forest Signal": {
        "mode": "dark",
        "fg": "#0A120E",
        "card": "#121C16",
        "accent": "#5CDB95",
        "accent2": "#A8E6CF",
        "text": "#E8F5E9",
        "muted": "#8FAE97",
        "success": "#69F0AE",
        "danger": "#EF5350",
        "console_bg": "#050A07",
        "console_fg": "#B9F6CA",
    },
    "Midnight Violet": {
        "mode": "dark",
        "fg": "#0D0B14",
        "card": "#161225",
        "accent": "#B388FF",
        "accent2": "#E1BEE7",
        "text": "#F3E5F5",
        "muted": "#9E9BB0",
        "success": "#69F0AE",
        "danger": "#FF5252",
        "console_bg": "#07050C",
        "console_fg": "#E1BEE7",
    },
}

DEFAULT_THEME = "Obsidian Gold"
